<?php

declare(strict_types=1);

namespace Tests\Feature;

use Tests\TestCase;

class SendingMoneyTest extends TestCase
{
    /**
     * Test that the XML can be generated by api
     */
    public function test_xml_can_be_generated_by_api(): void
    {
        $payload = [
            'PaymentRequestMessage' => [
                'TransferInfo' => [
                    'Reference' => 'e0f4763d-28ea-42d4-ac1c-c4013c242105',
                    'Date' => '2025-02-25 06:33:00+03',
                    'Amount' => '177.39',
                    'Currency' => 'SAR',
                ],
                'SenderInfo' => [
                    'AccountNumber' => 'SA6980000204608016212908',
                ],
                'ReceiverInfo' => [
                    'BankCode' => 'FDCSSARI',
                    'AccountNumber' => 'SA6980000204608016211111',
                    'BeneficiaryName' => 'Jane Doe',
                ],
                'Notes' => [
                    'Note' => [
                        'Lorem Epsum',
                        'Dolor Sit Amet',
                    ],
                ],
                'PaymentType' => '421',
                'ChargeDetails' => 'RB',
            ],
        ];

        $response = $this->postJson('/api/v1/generateXML', $payload);

        $response
            ->assertOk()
            ->assertContent(
                '<?xml version="1.0" encoding="utf-8"?>
<PaymentRequestMessage>
  <TransferInfo>
    <Reference>e0f4763d-28ea-42d4-ac1c-c4013c242105</Reference>
    <Date>2025-02-25 06:33:00+03</Date>
    <Amount>177.39</Amount>
    <Currency>SAR</Currency>
  </TransferInfo>
  <SenderInfo>
    <AccountNumber>SA6980000204608016212908</AccountNumber>
  </SenderInfo>
  <ReceiverInfo>
    <BankCode>FDCSSARI</BankCode>
    <AccountNumber>SA6980000204608016211111</AccountNumber>
    <BeneficiaryName>Jane Doe</BeneficiaryName>
  </ReceiverInfo>
  <Notes>
    <Note>Lorem Epsum</Note>
    <Note>Dolor Sit Amet</Note>
  </Notes>
  <PaymentType>421</PaymentType>
  <ChargeDetails>RB</ChargeDetails>
</PaymentRequestMessage>
');
    }

    /**
     * The Notes tag must not be present if there are no notes
     */
    public function test_notes_tag_is_not_present_if_no_notes(): void
    {
        $payload = [
            'PaymentRequestMessage' => [
                'TransferInfo' => [
                    'Reference' => 'e0f4763d-28ea-42d4-ac1c-c4013c242105',
                    'Date' => '2025-02-25 06:33:00+03',
                    'Amount' => '177.39',
                    'Currency' => 'SAR',
                ],
                'SenderInfo' => [
                    'AccountNumber' => 'SA6980000204608016212908',
                ],
                'ReceiverInfo' => [
                    'BankCode' => 'FDCSSARI',
                    'AccountNumber' => 'SA6980000204608016211111',
                    'BeneficiaryName' => 'Jane Doe',
                ],
                'Notes' => null,
                'PaymentType' => '421',
                'ChargeDetails' => 'RB',
            ],
        ];

        $response = $this->postJson('/api/v1/generateXML', $payload);

        $response
            ->assertOk()
            ->assertContent(
                '<?xml version="1.0" encoding="utf-8"?>
<PaymentRequestMessage>
  <TransferInfo>
    <Reference>e0f4763d-28ea-42d4-ac1c-c4013c242105</Reference>
    <Date>2025-02-25 06:33:00+03</Date>
    <Amount>177.39</Amount>
    <Currency>SAR</Currency>
  </TransferInfo>
  <SenderInfo>
    <AccountNumber>SA6980000204608016212908</AccountNumber>
  </SenderInfo>
  <ReceiverInfo>
    <BankCode>FDCSSARI</BankCode>
    <AccountNumber>SA6980000204608016211111</AccountNumber>
    <BeneficiaryName>Jane Doe</BeneficiaryName>
  </ReceiverInfo>
  <PaymentType>421</PaymentType>
  <ChargeDetails>RB</ChargeDetails>
</PaymentRequestMessage>
');
    }

    /**
     * The PaymentType tag must only be present if its value is other than 99
     */
    public function test_payment_type_tag_is_only_present_if_value_is_not_99(): void
    {
        $payload = [
            'PaymentRequestMessage' => [
                'TransferInfo' => [
                    'Reference' => 'e0f4763d-28ea-42d4-ac1c-c4013c242105',
                    'Date' => '2025-02-25 06:33:00+03',
                    'Amount' => '177.39',
                    'Currency' => 'SAR',
                ],
                'SenderInfo' => [
                    'AccountNumber' => 'SA6980000204608016212908',
                ],
                'ReceiverInfo' => [
                    'BankCode' => 'FDCSSARI',
                    'AccountNumber' => 'SA6980000204608016211111',
                    'BeneficiaryName' => 'Jane Doe',
                ],
                'Notes' => [
                    'Note' => [
                        'Lorem Epsum',
                        'Dolor Sit Amet',
                    ],
                ],
                'PaymentType' => '99',
                'ChargeDetails' => 'RB',
            ],
        ];

        $response = $this->postJson('/api/v1/generateXML', $payload);

        $response
            ->assertOk()
            ->assertContent(
                '<?xml version="1.0" encoding="utf-8"?>
<PaymentRequestMessage>
  <TransferInfo>
    <Reference>e0f4763d-28ea-42d4-ac1c-c4013c242105</Reference>
    <Date>2025-02-25 06:33:00+03</Date>
    <Amount>177.39</Amount>
    <Currency>SAR</Currency>
  </TransferInfo>
  <SenderInfo>
    <AccountNumber>SA6980000204608016212908</AccountNumber>
  </SenderInfo>
  <ReceiverInfo>
    <BankCode>FDCSSARI</BankCode>
    <AccountNumber>SA6980000204608016211111</AccountNumber>
    <BeneficiaryName>Jane Doe</BeneficiaryName>
  </ReceiverInfo>
  <Notes>
    <Note>Lorem Epsum</Note>
    <Note>Dolor Sit Amet</Note>
  </Notes>
  <ChargeDetails>RB</ChargeDetails>
</PaymentRequestMessage>
');
    }

    /**
     * The ChargeDetails tag must only be present if its value is other than SHA
     */
    public function test_charge_details_tag_is_only_present_if_value_is_not_sha(): void
    {
        $payload = [
            'PaymentRequestMessage' => [
                'TransferInfo' => [
                    'Reference' => 'e0f4763d-28ea-42d4-ac1c-c4013c242105',
                    'Date' => '2025-02-25 06:33:00+03',
                    'Amount' => '177.39',
                    'Currency' => 'SAR',
                ],
                'SenderInfo' => [
                    'AccountNumber' => 'SA6980000204608016212908',
                ],
                'ReceiverInfo' => [
                    'BankCode' => 'FDCSSARI',
                    'AccountNumber' => 'SA6980000204608016211111',
                    'BeneficiaryName' => 'Jane Doe',
                ],
                'Notes' => [
                    'Note' => [
                        'Lorem Epsum',
                        'Dolor Sit Amet',
                    ],
                ],
                'PaymentType' => '421',
                'ChargeDetails' => 'SHA',
            ],
        ];

        $response = $this->postJson('/api/v1/generateXML', $payload);

        $response
            ->assertOk()
            ->assertContent(
                '<?xml version="1.0" encoding="utf-8"?>
<PaymentRequestMessage>
  <TransferInfo>
    <Reference>e0f4763d-28ea-42d4-ac1c-c4013c242105</Reference>
    <Date>2025-02-25 06:33:00+03</Date>
    <Amount>177.39</Amount>
    <Currency>SAR</Currency>
  </TransferInfo>
  <SenderInfo>
    <AccountNumber>SA6980000204608016212908</AccountNumber>
  </SenderInfo>
  <ReceiverInfo>
    <BankCode>FDCSSARI</BankCode>
    <AccountNumber>SA6980000204608016211111</AccountNumber>
    <BeneficiaryName>Jane Doe</BeneficiaryName>
  </ReceiverInfo>
  <Notes>
    <Note>Lorem Epsum</Note>
    <Note>Dolor Sit Amet</Note>
  </Notes>
  <PaymentType>421</PaymentType>
</PaymentRequestMessage>
');
    }
}
